name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Create or verify .pylintrc
      run: |
        if [ ! -f .pylintrc ]; then
          echo "[MESSAGES CONTROL]" > .pylintrc
          echo "disable=W0718" >> .pylintrc
        else
          echo ".pylintrc file exists, skipping creation."
        fi
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=120 $(git ls-files '*.py')
